---
name: Publish

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    container: 
      image: pandoc/core:3.1-ubuntu
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup just
        uses: extractions/setup-just@v1

      - name: Install filters
        run: just install_filters

      - name: Build page
        run: just build

      - name: Publish artifact
        uses: actions/upload-artifact@v3
        with:
          name: website
          path: ./website
  deploy:
    needs: build
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: website

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website

      - name: Publish latest
        uses: "marvinpinto/action-automatic-releases@1.2.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            website