---
name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-22.04
    container: 
      image: pandoc/core:3.1-ubuntu
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup asdf
        uses: asdf-vm/actions/install@v2

      - name: Setup just
        uses: extractions/setup-just@v1

      - name: Install filters
        run: just install_filters

      - name: Build page
        run: just build

      - name: Publish artifact
        uses: actions/upload-artifact@v3
        with:
          name: website
          path: ./website
  release:
    name: Release
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - uses: "marvinpinto/action-automatic-releases@1.2.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            website
